[package]
name = "rsact"
version = "0.1.0"
edition = "2021"

[dependencies]
# rsact-reactive = {path = "./rsact-reactive", features = ["single-thread"]}
rsact-encoder = { path = "./rsact-encoder" }
rsact-ui = { path = "./rsact-ui" }

[workspace]
resolver = "2"
members = [
    "rsact-ui",
    "rsact-reactive",
    "rsact-encoder",
    "rsact-icons",
    "rsact-widgets",
    "rsact-macros",
]
# authors = ["hazer-hazer"]
# repository = "https://github.com/hazer-hazer/rsact"
# license = "MIT"
exclude = ["examples", "./rsact-icons/icon-libs"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
rsact-reactive = { path = "./rsact-reactive", default-features = false }
rsact-ui = { path = "./rsact-ui", default-features = false }
rsact-encoder = { path = "./rsact-encoder", default-features = false }
rsact-icons = { path = "./rsact-icons", default-features = false }
rsact-macros = { path = "./rsact-macros", default-features = false }
rsact-widgets = { path = "./rsact-widgets", default-features = false }

# [profile.dev]
# opt-level = 0
# debug = "full"

# [profile.example]
# inherits = "dev"
# opt-level = 3
# debug = "full"

[features]
std = ["rsact-ui/std"]
single-thread = ["rsact-ui/single-thread"]

# [profile.sandbox]
# inherits = "dev"
# opt-level = 3

# [profile.dev.package."embedded-graphics-simulator"]
# opt-level = 3

# [profile.test.package."embedded-graphics-simulator"]
# opt-level = 3
