[package]
name = "rsact"
version = "0.1.0"
edition = "2021"

[dependencies]
rsact-core = { path = "./rsact-core" }
rsact-ui = { path = "./rsact-ui" }

[features]

[workspace]
members = ["rsact-ui", "rsact-core"]
