[workspace]
resolver = "2"
members = ["rsact-ui", "rsact-core", "rsact-icons"]
exclude = ["examples"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
rsact-core = { path = "./rsact-core" }
rsact-ui = { path = "./rsact-ui" }

[profile.dev]
# opt-level = 0
debug = "full"
