edition = "2024"

condense_wildcard_suffixes = true
empty_item_single_line = true
fn_args_layout = "Tall"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
group_imports = "One"
imports_granularity = "Crate"
imports_layout = "Mixed"
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 80
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
tab_spaces = 4
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
