//! Regenerates a self-contained static HTML viewer over the snapshot dir. All
//! snapshots are embedded inline as JSON, so the page opens straight from
//! `file://` (no server, no directory listing needed) — matching the
//! "static HTML viewer over the snapshot dir" contract.

use crate::snapshot::Snapshot;
use std::{fs, io, path::Path};

pub fn regenerate(dir: &Path) -> io::Result<()> {
    let mut snaps: Vec<Snapshot> = Vec::new();
    if dir.is_dir() {
        for entry in fs::read_dir(dir)? {
            let path = entry?.path();
            if path.extension().and_then(|e| e.to_str()) == Some("json") {
                if let Ok(s) = Snapshot::load(&path) {
                    snaps.push(s);
                }
            }
        }
    }
    snaps.sort_by_key(|s| s.recorded_at);

    let data = serde_json::to_string(&snaps).unwrap();
    let out = dir.parent().unwrap_or(Path::new(".")).join("index.html");
    fs::write(&out, page(&data))?;
    println!("wrote {} ({} snapshots)", out.display(), snaps.len());
    Ok(())
}

fn page(data: &str) -> String {
    // Single template; the snapshot array is spliced in as inline JSON.
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>rsact metrics</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font: 14px/1.5 ui-monospace, SFMono-Regular, Menlo, monospace; margin: 2rem; }}
  h1 {{ font-size: 1.2rem; }}
  h2 {{ font-size: 1rem; margin-top: 2rem; }}
  table {{ border-collapse: collapse; margin: .5rem 0 1.5rem; }}
  th, td {{ border: 1px solid gray; padding: .2rem .6rem; text-align: right; }}
  th:first-child, td:first-child {{ text-align: left; }}
  caption {{ text-align: left; font-weight: bold; margin-bottom: .3rem; }}
  .dirty {{ opacity: .6; }}
  .muted {{ color: gray; }}
</style>
</head>
<body>
<h1>rsact framework metrics</h1>
<p class="muted">Layer-1 metrics per commit. Newest column on the right. Generated by <code>metrics-probe html</code>.</p>
<div id="root"></div>
<script>
const SNAPSHOTS = {data};
const METRICS = [
  ["nodes_total", s => s.counts.total],
  ["signals", s => s.counts.signals],
  ["memos", s => s.counts.memos],
  ["effects", s => s.counts.effects],
  ["observers", s => s.counts.observers],
  ["stored", s => s.counts.stored],
  ["heap_live_bytes", s => s.heap_live_bytes],
  ["heap_peak_bytes", s => s.heap_peak_bytes],
  ["build_allocs", s => s.build_allocs],
  ["idle_frame_allocs", s => s.idle_frame_allocs],
  ["change_frame_allocs", s => s.change_frame_allocs],
  ["layout_visits", s => s.layout ? s.layout.visits : null],
  ["layout_measures", s => s.layout ? s.layout.measures : null],
];
const root = document.getElementById("root");
if (!SNAPSHOTS.length) {{
  root.innerHTML = "<p>No snapshots yet. Run <code>cargo run -p metrics-probe -- record</code>.</p>";
}} else {{
  const names = [...new Set(SNAPSHOTS.flatMap(s => s.scenarios.map(x => x.name)))];
  for (const name of names) {{
    const table = document.createElement("table");
    const cap = document.createElement("caption");
    cap.textContent = name;
    table.appendChild(cap);
    const head = document.createElement("tr");
    head.innerHTML = "<th>metric</th>" + SNAPSHOTS.map(s => {{
      const rev = s.git_rev.slice(0, 8) + (s.git_dirty ? "*" : "");
      return `<th class="${{s.git_dirty ? "dirty" : ""}}">${{rev}}</th>`;
    }}).join("");
    table.appendChild(head);
    for (const [label, fn] of METRICS) {{
      const cells = SNAPSHOTS.map(s => {{
        const sc = s.scenarios.find(x => x.name === name);
        const v = sc ? fn(sc) : null;
        return `<td>${{v === null || v === undefined ? '<span class=muted>-</span>' : v}}</td>`;
      }});
      // Skip all-empty rows (e.g. layout counters when feature was off).
      if (cells.every(c => c.includes("muted"))) continue;
      table.innerHTML += `<tr><td>${{label}}</td>${{cells.join("")}}</tr>`;
    }}
    root.appendChild(table);
  }}
}}
</script>
</body>
</html>
"#
    )
}
