[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.87"

[lib]
proc-macro = true

[package]
edition.workspace = true
name = "rsact-macros"
version.workspace = true

[lints]
workspace = true
