[package]
name = "rsact-reactive"
edition.workspace = true
version.workspace = true

[dependencies]
lazy_static = { version = "1.5.0", default-features = false }
log = { version = "0.4.22", default-features = false }
slotmap = { version = "1.0.7", default-features = false }
once_cell = { version = "1.19.0", default-features = false }

[dev-dependencies]
criterion = "0.5.1"

[features]
default = []
std = []

[[bench]]
name = "reactivity"
harness = false
