[dependencies]
log = {workspace = true}
once_cell = {workspace = true}
replace_with = {workspace = true}
rsact-macros = {workspace = true}
slotmap = {workspace = true}

[dev-dependencies]
criterion = "0.5.1"

[package]
edition.workspace = true
name = "rsact-reactive"
version.workspace = true

[features]
default = []
single-thread = []
std = []

[[bench]]
harness = false
name = "reactivity"

[lints]
workspace = true
