[package]
edition.workspace = true
name = "rsact-ui"
version.workspace = true

[dependencies]
bitflags = {workspace = true}
defmt = {workspace = true, optional = true}
derivative = {workspace = true}
embedded-graphics = {workspace = true}
embedded-graphics-core = {workspace = true}
embedded-graphics-simulator = {workspace = true, optional = true}
embedded-text = {workspace = true}
embedded-time = {workspace = true}
log = {workspace = true}
micromath = {workspace = true}
num = {workspace = true}
rsact-icons = {workspace = true, features = ["common", "all-sizes"]}
rsact-reactive = {workspace = true}
tinyvec = {workspace = true}
u8g2-fonts = {workspace = true}

[dev-dependencies]
cap = {workspace = true}
fake = "4.0.0"
rand = "0.9"
paw = {path = "../../paw"}

[features]
default = []

debug-info = []
defmt = ["dep:defmt"]
simulator = ["dep:embedded-graphics-simulator"]
single-thread = ["rsact-reactive/single-thread"]
std = ["log/std", "rsact-reactive/std"]
# TODO: Print pretty blocks in terminal showing layout problems: overflows, insufficient sizes, etc.
layout-diagnostics = []

[[example]]
name = "animation"
required-features = ["std", "simulator"]

[[example]]
name = "flex"
required-features = ["std", "simulator"]

[lints]
workspace = true
