[package]
name = "rsact-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
rsact-core = { path = "../rsact-core" }
defmt = { version = "0.3.8", optional = true }
embedded-graphics = "0.8.1"
embedded-graphics-core = "0.4.0"
embedded-text = "0.7.2"
log = { version = "0.4.22", default-features = false, features = [
    "max_level_off",
] }
env_logger = "0.11.5"
num = "0.4.3"
embedded-graphics-simulator = { version = "0.6.0", optional = true }
embedded-canvas = "0.3.1"

[features]
default = []

defmt = ["dep:defmt"]
std = ["log/std"]
simulator = ["dep:embedded-graphics-simulator"]

[profile.dev]
# opt-level = 0
debug = "full"

[dev-dependencies]
embedded-graphics-simulator = "0.6.0"
rand = "0.8.5"
