[package]
name = "rsact-ui"
version.workspace = true
edition.workspace = true

[dependencies]
rsact-reactive = { path = "../rsact-reactive" }
rsact-icons = {path = "../rsact-icons", default-features = false, features = ["system", "all-sizes"]}
defmt = { version = "0.3.8", optional = true }
embedded-graphics = "0.8.1"
embedded-graphics-core = "0.4.0"
embedded-text = "0.7.2"
log = { version = "0.4.22", default-features = false, features = [
    "max_level_off",
] }
env_logger = "0.11.5"
num = "0.4.3"
embedded-graphics-simulator = { version = "0.7.0", optional = true }
embedded-canvas = "0.3.1"
bitflags = "2.6.0"
derivative = { version = "2.2.0", default-features = false, features = [
    "use_core",
] }

[dev-dependencies]
embedded-graphics-simulator = { version = "0.7.0" }
rand = "0.8.5"

[features]
default = []

defmt = ["dep:defmt"]
std = ["log/std", "rsact-reactive/std"]
single-thread = ["rsact-reactive/single-thread"]
simulator = ["dep:embedded-graphics-simulator"]
