graph TD

signal4294967297(" signal: u32 (clean)")




signal4294967298(" signal: alloc::vec::Vec<rsact_ui::event::message::UiMessage<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (clean)")




memo4294967299([" memo: u32 (dirty)"])




signal4294967300(" signal: alloc::string::String (clean)")




signal4294967301(" signal: std::time::Instant (clean)")




signal4294967302(" signal: bool (clean)")

effect4294967312 ===o |sub|signal4294967302
effect4294967312[[" effect: () (clean)"]]


signal4294967302 ===o |source|effect4294967312


effect4294967312 --> |clean|effect4294967312




signal4294967303(" signal: rsact_ui::value::RangeU8<0, u8::MAX> (clean)")




signal4294967304(" signal: rsact_ui::layout::Layout (clean)")




memoChain4294967305(((" memoChain: rsact_ui::widget::bar::BarStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967306([" memo: alloc::string::String (dirty)"])




memoChain4294967307(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967308(" signal: rsact_ui::layout::Layout (clean)")

effect4294967604 ===o |sub|signal4294967308
effect4294967604[[" effect: () (clean)"]]


signal4294967308 ===o |source|effect4294967604

signal4294967309 ===o |source|effect4294967604
signal4294967309(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967604 ===o |sub|signal4294967309



signal4294967309 --> |dirten|signal4294967309


effect4294967604 --> |clean|effect4294967604





memo4294967310([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])




signal4294967311(" 'Layout tree' signal: rsact_ui::layout::Layout (clean)")



signal4294967311 --> |clean|signal4294967311


signal4294967313(" signal: rsact_ui::font::FontSize (dirty)")



signal4294967313 --> |dirten|signal4294967313

signal4294967314(" signal: rsact_ui::layout::Layout (clean)")




memoChain4294967315(((" memoChain: rsact_ui::widget::icon::IconStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967316([" memo: alloc::string::String (dirty)"])




memoChain4294967317(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967318(" signal: rsact_ui::layout::Layout (clean)")

effect4294967638 ===o |sub|signal4294967318
effect4294967638[[" effect: () (clean)"]]


signal4294967318 ===o |source|effect4294967638

signal4294967319 ===o |source|effect4294967638
signal4294967319(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967638 ===o |sub|signal4294967319



signal4294967319 --> |dirten|signal4294967319


effect4294967638 --> |clean|effect4294967638





memo4294967320([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])




signal4294967321(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967321
effect4294967637[[" effect: () (clean)"]]


signal4294967321 ===o |source|effect4294967637

signal4294967323 ===o |source|effect4294967637
signal4294967323(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967323



signal4294967323 --> |clean|signal4294967323

signal4294967327 ===o |source|effect4294967637
signal4294967327(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967327




signal4294967329 ===o |source|effect4294967637
signal4294967329(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967329



signal4294967329 --> |clean|signal4294967329

signal4294967333 ===o |source|effect4294967637
signal4294967333(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967333




signal4294967335 ===o |source|effect4294967637
signal4294967335(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967335



signal4294967335 --> |clean|signal4294967335

signal4294967339 ===o |source|effect4294967637
signal4294967339(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967339




signal4294967341 ===o |source|effect4294967637
signal4294967341(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967341



signal4294967341 --> |clean|signal4294967341

signal4294967345 ===o |source|effect4294967637
signal4294967345(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967345




signal4294967347 ===o |source|effect4294967637
signal4294967347(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967347



signal4294967347 --> |clean|signal4294967347

signal4294967351 ===o |source|effect4294967637
signal4294967351(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967351




signal4294967353 ===o |source|effect4294967637
signal4294967353(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967353



signal4294967353 --> |clean|signal4294967353

signal4294967357 ===o |source|effect4294967637
signal4294967357(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967357




signal4294967359 ===o |source|effect4294967637
signal4294967359(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967359



signal4294967359 --> |clean|signal4294967359

signal4294967363 ===o |source|effect4294967637
signal4294967363(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967363




signal4294967365 ===o |source|effect4294967637
signal4294967365(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967365



signal4294967365 --> |clean|signal4294967365

signal4294967369 ===o |source|effect4294967637
signal4294967369(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967369




signal4294967371 ===o |source|effect4294967637
signal4294967371(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967371



signal4294967371 --> |clean|signal4294967371

signal4294967375 ===o |source|effect4294967637
signal4294967375(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967375




signal4294967377 ===o |source|effect4294967637
signal4294967377(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967377



signal4294967377 --> |clean|signal4294967377

signal4294967381 ===o |source|effect4294967637
signal4294967381(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967381




signal4294967383 ===o |source|effect4294967637
signal4294967383(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967383



signal4294967383 --> |clean|signal4294967383

signal4294967387 ===o |source|effect4294967637
signal4294967387(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967387




signal4294967389 ===o |source|effect4294967637
signal4294967389(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967389



signal4294967389 --> |clean|signal4294967389

signal4294967393 ===o |source|effect4294967637
signal4294967393(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967393




signal4294967395 ===o |source|effect4294967637
signal4294967395(" signal: rsact_ui::layout::Layout (clean)")

effect4294967637 ===o |sub|signal4294967395



signal4294967395 --> |clean|signal4294967395

signal4294967397 ===o |source|effect4294967637
signal4294967397(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967637 ===o |sub|signal4294967397



signal4294967397 --> |dirten|signal4294967397


effect4294967637 --> |clean|effect4294967637



signal4294967321 --> |clean|signal4294967321

signal4294967322(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967324(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967325([" memo: alloc::string::String (dirty)"])




memoChain4294967326(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967328(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967330(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967331([" memo: alloc::string::String (dirty)"])




memoChain4294967332(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967334(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967336(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967337([" memo: alloc::string::String (dirty)"])




memoChain4294967338(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967340(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967342(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967343([" memo: alloc::string::String (dirty)"])




memoChain4294967344(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967346(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967348(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967349([" memo: alloc::string::String (dirty)"])




memoChain4294967350(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967352(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967354(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967355([" memo: alloc::string::String (dirty)"])




memoChain4294967356(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967358(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967360(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967361([" memo: alloc::string::String (dirty)"])




memoChain4294967362(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967364(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967366(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967367([" memo: alloc::string::String (dirty)"])




memoChain4294967368(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967370(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967372(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967373([" memo: alloc::string::String (dirty)"])




memoChain4294967374(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967376(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967378(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967379([" memo: alloc::string::String (dirty)"])




memoChain4294967380(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967382(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967384(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967385([" memo: alloc::string::String (dirty)"])




memoChain4294967386(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967388(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967390(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967391([" memo: alloc::string::String (dirty)"])




memoChain4294967392(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967394(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967396(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memo4294967398([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])




signal4294967399(" signal: rsact_ui::layout::Layout (clean)")



signal4294967399 --> |clean|signal4294967399

signal4294967400(" signal: rsact_ui::widget::scrollable::ScrollableState (clean)")




signal4294967401(" 'Layout tree' signal: rsact_ui::layout::Layout (clean)")



signal4294967401 --> |clean|signal4294967401

memoChain4294967402(((" memoChain: rsact_ui::widget::scrollable::ScrollableStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967403(" signal: embedded_graphics_core::geometry::point::Point (clean)")




signal4294967404(" signal: i32 (clean)")




signal4294967405(" signal: bool (clean)")

effect4294967407 ===o |sub|signal4294967405
effect4294967407[[" effect: () (clean)"]]


signal4294967405 ===o |source|effect4294967407


effect4294967407 --> |clean|effect4294967407




signal4294967406(" signal: std::time::Instant (clean)")





signal4294967408(" signal: rsact_ui::font::FontSize (dirty)")



signal4294967408 --> |dirten|signal4294967408

signal4294967409(" signal: rsact_ui::layout::Layout (clean)")




memoChain4294967410(((" memoChain: rsact_ui::widget::icon::IconStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967411([" memo: alloc::string::String (dirty)"])




memoChain4294967412(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967413(" signal: rsact_ui::layout::Layout (clean)")

effect4294967614 ===o |sub|signal4294967413
effect4294967614[[" effect: () (clean)"]]


signal4294967413 ===o |source|effect4294967614

signal4294967414 ===o |source|effect4294967614
signal4294967414(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967614 ===o |sub|signal4294967414



signal4294967414 --> |dirten|signal4294967414


effect4294967614 --> |clean|effect4294967614





memo4294967415([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])




signal4294967416(" signal: rsact_ui::layout::Layout (clean)")

effect4294967613 ===o |sub|signal4294967416
effect4294967613[[" effect: () (clean)"]]


signal4294967416 ===o |source|effect4294967613

signal4294967418 ===o |source|effect4294967613
signal4294967418(" signal: rsact_ui::layout::Layout (clean)")

effect4294967613 ===o |sub|signal4294967418



signal4294967418 --> |clean|signal4294967418

signal4294967422 ===o |source|effect4294967613
signal4294967422(" signal: rsact_ui::layout::Layout (clean)")

effect4294967613 ===o |sub|signal4294967422




signal4294967425 ===o |source|effect4294967613
signal4294967425(" signal: rsact_ui::layout::Layout (clean)")

effect4294967613 ===o |sub|signal4294967425




signal4294967427 ===o |source|effect4294967613
signal4294967427(" signal: rsact_ui::layout::Layout (clean)")

effect4294967613 ===o |sub|signal4294967427



signal4294967427 --> |clean|signal4294967427

signal4294967429 ===o |source|effect4294967613
signal4294967429(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967613 ===o |sub|signal4294967429



signal4294967429 --> |dirten|signal4294967429


effect4294967613 --> |clean|effect4294967613



signal4294967416 --> |clean|signal4294967416

signal4294967417(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967419(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967420([" memo: alloc::string::String (dirty)"])




memoChain4294967421(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memo4294967423([" memo: alloc::string::String (dirty)"])




memoChain4294967424(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967426(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967428(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memo4294967430([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])




signal4294967431(" signal: rsact_ui::layout::Layout (clean)")

effect4294967612 ===o |sub|signal4294967431
effect4294967612[[" effect: () (clean)"]]


signal4294967431 ===o |source|effect4294967612

signal4294967452 ===o |source|effect4294967612
signal4294967452(" signal: rsact_ui::layout::Layout (clean)")

effect4294967612 ===o |sub|signal4294967452



signal4294967452 --> |clean|signal4294967452

signal4294967470 ===o |source|effect4294967612
signal4294967470(" signal: rsact_ui::layout::Layout (clean)")

effect4294967612 ===o |sub|signal4294967470



signal4294967470 --> |clean|signal4294967470

signal4294967479 ===o |source|effect4294967612
signal4294967479(" signal: rsact_ui::layout::Layout (clean)")

effect4294967612 ===o |sub|signal4294967479



signal4294967479 --> |clean|signal4294967479

signal4294967480 ===o |source|effect4294967612
signal4294967480(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967612 ===o |sub|signal4294967480



signal4294967480 --> |dirten|signal4294967480


effect4294967612 --> |clean|effect4294967612



signal4294967431 --> |clean|signal4294967431

memo4294967432([" memo: alloc::string::String (dirty)"])




memoChain4294967433(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967434(" signal: rsact_ui::layout::Layout (clean)")

effect4294967615 ===o |sub|signal4294967434
effect4294967615[[" effect: () (clean)"]]


signal4294967434 ===o |source|effect4294967615

signal4294967436 ===o |source|effect4294967615
signal4294967436(" signal: rsact_ui::layout::Layout (clean)")

effect4294967615 ===o |sub|signal4294967436



signal4294967436 --> |clean|signal4294967436

signal4294967440 ===o |source|effect4294967615
signal4294967440(" signal: rsact_ui::layout::Layout (clean)")

effect4294967615 ===o |sub|signal4294967440




signal4294967442 ===o |source|effect4294967615
signal4294967442(" signal: rsact_ui::layout::Layout (clean)")

effect4294967615 ===o |sub|signal4294967442



signal4294967442 --> |clean|signal4294967442

signal4294967446 ===o |source|effect4294967615
signal4294967446(" signal: rsact_ui::layout::Layout (clean)")

effect4294967615 ===o |sub|signal4294967446




signal4294967448 ===o |source|effect4294967615
signal4294967448(" signal: rsact_ui::layout::Layout (clean)")

effect4294967615 ===o |sub|signal4294967448



signal4294967448 --> |clean|signal4294967448

signal4294967450 ===o |source|effect4294967615
signal4294967450(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967615 ===o |sub|signal4294967450



signal4294967450 --> |dirten|signal4294967450


effect4294967615 --> |clean|effect4294967615




signal4294967435(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967437(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967438([" memo: alloc::string::String (dirty)"])




memoChain4294967439(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967441(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967443(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967444([" memo: alloc::string::String (dirty)"])




memoChain4294967445(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967447(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967449(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memo4294967451([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])





memo4294967453([" memo: alloc::string::String (dirty)"])




memoChain4294967454(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967455(" signal: rsact_ui::layout::Layout (clean)")

effect4294967616 ===o |sub|signal4294967455
effect4294967616[[" effect: () (clean)"]]


signal4294967455 ===o |source|effect4294967616

signal4294967457 ===o |source|effect4294967616
signal4294967457(" signal: rsact_ui::layout::Layout (clean)")

effect4294967616 ===o |sub|signal4294967457



signal4294967457 --> |clean|signal4294967457

signal4294967461 ===o |source|effect4294967616
signal4294967461(" signal: rsact_ui::layout::Layout (clean)")

effect4294967616 ===o |sub|signal4294967461




signal4294967464 ===o |source|effect4294967616
signal4294967464(" signal: rsact_ui::layout::Layout (clean)")

effect4294967616 ===o |sub|signal4294967464




signal4294967466 ===o |source|effect4294967616
signal4294967466(" signal: rsact_ui::layout::Layout (clean)")

effect4294967616 ===o |sub|signal4294967466



signal4294967466 --> |clean|signal4294967466

signal4294967468 ===o |source|effect4294967616
signal4294967468(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967616 ===o |sub|signal4294967468



signal4294967468 --> |dirten|signal4294967468


effect4294967616 --> |clean|effect4294967616




signal4294967456(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967458(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967459([" memo: alloc::string::String (dirty)"])




memoChain4294967460(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memo4294967462([" memo: alloc::string::String (dirty)"])




memoChain4294967463(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967465(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967467(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memo4294967469([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])





memo4294967471([" memo: alloc::string::String (dirty)"])




memoChain4294967472(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967473(" signal: rsact_ui::layout::Layout (clean)")

effect4294967617 ===o |sub|signal4294967473
effect4294967617[[" effect: () (clean)"]]


signal4294967473 ===o |source|effect4294967617

signal4294967475 ===o |source|effect4294967617
signal4294967475(" signal: rsact_ui::layout::Layout (clean)")

effect4294967617 ===o |sub|signal4294967475



signal4294967475 --> |clean|signal4294967475

signal4294967477 ===o |source|effect4294967617
signal4294967477(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967617 ===o |sub|signal4294967477



signal4294967477 --> |dirten|signal4294967477


effect4294967617 --> |clean|effect4294967617




signal4294967474(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967476(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memo4294967478([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])






memo4294967481([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])




signal4294967482(" 'Layout tree' signal: rsact_ui::layout::Layout (clean)")



signal4294967482 --> |clean|signal4294967482

signal4294967483(" signal: rsact_ui::value::RangeU8<0, 110> (clean)")




signal4294967484(" signal: rsact_ui::value::RangeU8<0, 250> (clean)")




signal4294967485(" signal: std::time::Instant (clean)")




signal4294967486(" signal: bool (clean)")

effect4294967487 ===o |sub|signal4294967486
effect4294967487[[" effect: () (clean)"]]


signal4294967486 ===o |source|effect4294967487


effect4294967487 --> |clean|effect4294967487





signal4294967488(" signal: rsact_ui::font::FontSize (dirty)")



signal4294967488 --> |dirten|signal4294967488

signal4294967489(" signal: rsact_ui::layout::Layout (clean)")




memoChain4294967490(((" memoChain: rsact_ui::widget::icon::IconStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967491([" memo: alloc::string::String (dirty)"])




memoChain4294967492(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967493(" signal: rsact_ui::layout::Layout (clean)")

effect4294967627 ===o |sub|signal4294967493
effect4294967627[[" effect: () (clean)"]]


signal4294967493 ===o |source|effect4294967627

signal4294967494 ===o |source|effect4294967627
signal4294967494(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967627 ===o |sub|signal4294967494



signal4294967494 --> |dirten|signal4294967494


effect4294967627 --> |clean|effect4294967627





memo4294967495([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])




signal4294967496(" signal: rsact_ui::layout::Layout (clean)")

effect4294967626 ===o |sub|signal4294967496
effect4294967626[[" effect: () (clean)"]]


signal4294967496 ===o |source|effect4294967626

signal4294967498 ===o |source|effect4294967626
signal4294967498(" signal: rsact_ui::layout::Layout (clean)")

effect4294967626 ===o |sub|signal4294967498



signal4294967498 --> |clean|signal4294967498

signal4294967502 ===o |source|effect4294967626
signal4294967502(" signal: rsact_ui::layout::Layout (clean)")

effect4294967626 ===o |sub|signal4294967502




signal4294967504 ===o |source|effect4294967626
signal4294967504(" signal: rsact_ui::layout::Layout (clean)")

effect4294967626 ===o |sub|signal4294967504



signal4294967504 --> |clean|signal4294967504

signal4294967506 ===o |source|effect4294967626
signal4294967506(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967626 ===o |sub|signal4294967506



signal4294967506 --> |dirten|signal4294967506


effect4294967626 --> |clean|effect4294967626



signal4294967496 --> |clean|signal4294967496

signal4294967497(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967499(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967500([" memo: alloc::string::String (dirty)"])




memoChain4294967501(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





signal4294967503(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967505(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memo4294967507([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])




signal4294967508(" signal: rsact_ui::layout::Layout (clean)")

effect4294967625 ===o |sub|signal4294967508
effect4294967625[[" effect: () (clean)"]]


signal4294967508 ===o |source|effect4294967625

signal4294967520 ===o |source|effect4294967625
signal4294967520(" signal: rsact_ui::layout::Layout (clean)")

effect4294967625 ===o |sub|signal4294967520



signal4294967520 --> |clean|signal4294967520

signal4294967532 ===o |source|effect4294967625
signal4294967532(" signal: rsact_ui::layout::Layout (clean)")

effect4294967625 ===o |sub|signal4294967532



signal4294967532 --> |clean|signal4294967532

signal4294967533 ===o |source|effect4294967625
signal4294967533(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967625 ===o |sub|signal4294967533



signal4294967533 --> |dirten|signal4294967533


effect4294967625 --> |clean|effect4294967625



signal4294967508 --> |clean|signal4294967508

memo4294967509([" memo: alloc::string::String (dirty)"])




memoChain4294967510(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967511(" signal: rsact_ui::layout::Layout (clean)")

effect4294967628 ===o |sub|signal4294967511
effect4294967628[[" effect: () (clean)"]]


signal4294967511 ===o |source|effect4294967628

signal4294967517 ===o |source|effect4294967628
signal4294967517(" signal: rsact_ui::layout::Layout (clean)")

effect4294967628 ===o |sub|signal4294967517




signal4294967518 ===o |source|effect4294967628
signal4294967518(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967628 ===o |sub|signal4294967518



signal4294967518 --> |dirten|signal4294967518


effect4294967628 --> |clean|effect4294967628




signal4294967512(" signal: rsact_ui::layout::Layout (clean)")




signal4294967513(" signal: rsact_ui::widget::knob::KnobState (clean)")




memoChain4294967514(((" memoChain: rsact_ui::widget::knob::KnobStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967515([" memo: alloc::string::String (dirty)"])




memoChain4294967516(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))






memo4294967519([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])





memo4294967521([" memo: alloc::string::String (dirty)"])




memoChain4294967522(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




signal4294967523(" signal: rsact_ui::layout::Layout (clean)")

effect4294967629 ===o |sub|signal4294967523
effect4294967629[[" effect: () (clean)"]]


signal4294967523 ===o |source|effect4294967629

signal4294967529 ===o |source|effect4294967629
signal4294967529(" signal: rsact_ui::layout::Layout (clean)")

effect4294967629 ===o |sub|signal4294967529




signal4294967530 ===o |source|effect4294967629
signal4294967530(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (dirty)")

effect4294967629 ===o |sub|signal4294967530



signal4294967530 --> |dirten|signal4294967530


effect4294967629 --> |clean|effect4294967629




signal4294967524(" signal: rsact_ui::layout::Layout (clean)")




signal4294967525(" signal: rsact_ui::widget::knob::KnobState (clean)")




memoChain4294967526(((" memoChain: rsact_ui::widget::knob::KnobStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))




memo4294967527([" memo: alloc::string::String (dirty)"])




memoChain4294967528(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))






memo4294967531([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])






memo4294967534([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (dirty)"])




signal4294967535(" 'Layout tree' signal: rsact_ui::layout::Layout (clean)")



signal4294967535 --> |clean|signal4294967535

signal4294967536(" signal: rsact_ui::font::FontSize (clean)")

memo4294967594 ===o |sub|signal4294967536
memo4294967594([" 'Layout model' memo: rsact_ui::layout::LayoutModel (clean)"])

observer4294967647 ===o |sub|memo4294967594
observer4294967647{" observer (clean)"}


memo4294967594 ===o |source|observer4294967647

signal4294967595 ===o |source|observer4294967647
signal4294967595(" 'Page style' signal: rsact_ui::page::PageStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (clean)")

observer4294967647 ===o |sub|signal4294967595




observer4294967648 ===o |source|observer4294967647
observer4294967648{" observer (clean)"}

observer4294967647 ===o |sub|observer4294967648

observer4294967648 ===o |sub|observer4294967648


signal4294967536 ===o |source|observer4294967648

memoChain4294967538 ===o |source|observer4294967648
memoChain4294967538(((" memoChain: rsact_ui::widget::icon::IconStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (clean)")))

observer4294967648 ===o |sub|memoChain4294967538


memo4294967582 ===o |source|memoChain4294967538
memo4294967582([" memo: rsact_ui::style::NullStyler (clean)"])

memoChain4294967538 ===o |sub|memo4294967582

memoChain4294967547 ===o |sub|memo4294967582
memoChain4294967547(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (clean)")))


signal4294967545 ===o |source|memoChain4294967547
signal4294967545(" signal: rsact_ui::widget::button::ButtonState (clean)")

memoChain4294967547 ===o |sub|signal4294967545




memo4294967582 ===o |source|memoChain4294967547


memoChain4294967547 --> |clean|memoChain4294967547

memoChain4294967577 ===o |sub|memo4294967582
memoChain4294967577(((" memoChain: rsact_ui::widget::scrollable::ScrollableStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (clean)")))


signal4294967575 ===o |source|memoChain4294967577
signal4294967575(" signal: rsact_ui::widget::scrollable::ScrollableState (clean)")

memoChain4294967577 ===o |sub|signal4294967575




memo4294967582 ===o |source|memoChain4294967577


memoChain4294967577 --> |clean|memoChain4294967577



memo4294967582 --> |clean|memo4294967582


memoChain4294967538 --> |clean|memoChain4294967538

signal4294967542 ===o |source|observer4294967648
signal4294967542(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (clean)")

memo4294967543 ===o |sub|signal4294967542
memo4294967543([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (clean)"])

memo4294967594 ===o |sub|memo4294967543


signal4294967542 ===o |source|memo4294967543


memo4294967543 --> |clean|memo4294967543

effect4294967586 ===o |sub|signal4294967542
effect4294967586[[" effect: () (dirty)"]]


signal4294967541 ===o |source|effect4294967586
signal4294967541(" signal: rsact_ui::layout::Layout (clean)")

effect4294967586 ===o |sub|signal4294967541

memo4294967594 ===o |sub|signal4294967541




signal4294967542 ===o |source|effect4294967586


signal4294967542 ===> |dirten|effect4294967586



signal4294967542 --> |clean|signal4294967542

signal4294967546 ===o |source|observer4294967648
signal4294967546(" signal: rsact_ui::layout::Layout (clean)")

effect4294967585 ===o |sub|signal4294967546
effect4294967585[[" effect: () (dirty)"]]


signal4294967544 ===o |source|effect4294967585
signal4294967544(" signal: rsact_ui::layout::Layout (clean)")

effect4294967585 ===o |sub|signal4294967544

memo4294967594 ===o |sub|signal4294967544



signal4294967544 --> |clean|signal4294967544

signal4294967546 ===o |source|effect4294967585

signal4294967556 ===o |source|effect4294967585
signal4294967556(" signal: rsact_ui::layout::Layout (clean)")

effect4294967585 ===o |sub|signal4294967556

memo4294967594 ===o |sub|signal4294967556



signal4294967556 --> |clean|signal4294967556

signal4294967558 ===o |source|effect4294967585
signal4294967558(" signal: rsact_ui::layout::Layout (clean)")

effect4294967585 ===o |sub|signal4294967558

memo4294967594 ===o |sub|signal4294967558



signal4294967558 --> |clean|signal4294967558

signal4294967568 ===o |source|effect4294967585
signal4294967568(" signal: rsact_ui::layout::Layout (clean)")

effect4294967585 ===o |sub|signal4294967568

memo4294967594 ===o |sub|signal4294967568



signal4294967568 --> |clean|signal4294967568

signal4294967570 ===o |source|effect4294967585
signal4294967570(" signal: rsact_ui::layout::Layout (clean)")

effect4294967585 ===o |sub|signal4294967570

memo4294967594 ===o |sub|signal4294967570



signal4294967570 --> |clean|signal4294967570

signal4294967572 ===o |source|effect4294967585

signal4294967572(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (clean)")

memo4294967573 ===o |sub|signal4294967572
memo4294967573([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (clean)"])

memo4294967594 ===o |sub|memo4294967573


signal4294967572 ===o |source|memo4294967573


memo4294967573 --> |clean|memo4294967573

effect4294967585 ===o |sub|signal4294967572

memo4294967590 ===o |sub|signal4294967572
memo4294967590([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (clean)"])

memo4294967593 ===o |sub|memo4294967590
memo4294967593([" 'Focusable' memo: alloc::vec::Vec<rsact_ui::el::ElId> (clean)"])


memo4294967589 ===o |source|memo4294967593
memo4294967589([" memo: rsact_ui::widget::Meta (clean)"])

memo4294967593 ===o |sub|memo4294967589



memo4294967589 --> |clean|memo4294967589

memo4294967590 ===o |source|memo4294967593

memo4294967591 ===o |source|memo4294967593
memo4294967591([" memo: rsact_ui::widget::Meta (clean)"])

memo4294967593 ===o |sub|memo4294967591



memo4294967591 --> |clean|memo4294967591

memo4294967592 ===o |source|memo4294967593
memo4294967592([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (clean)"])

memo4294967593 ===o |sub|memo4294967592



memo4294967592 --> |clean|memo4294967592

memo4294967597 ===o |source|memo4294967593
memo4294967597([" memo: rsact_ui::widget::Meta (clean)"])

memo4294967593 ===o |sub|memo4294967597



memo4294967597 --> |clean|memo4294967597

memo4294967598 ===o |source|memo4294967593
memo4294967598([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (clean)"])

memo4294967593 ===o |sub|memo4294967598



memo4294967598 --> |clean|memo4294967598

memo4294967599 ===o |source|memo4294967593
memo4294967599([" memo: rsact_ui::widget::Meta (clean)"])

memo4294967593 ===o |sub|memo4294967599



memo4294967599 --> |clean|memo4294967599

memo4294967600 ===o |source|memo4294967593
memo4294967600([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (clean)"])

memo4294967593 ===o |sub|memo4294967600



memo4294967600 --> |clean|memo4294967600

memo4294967601 ===o |source|memo4294967593
memo4294967601([" memo: rsact_ui::widget::Meta (clean)"])

memo4294967593 ===o |sub|memo4294967601



memo4294967601 --> |clean|memo4294967601

memo4294967602 ===o |source|memo4294967593
memo4294967602([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (clean)"])

memo4294967593 ===o |sub|memo4294967602



memo4294967602 --> |clean|memo4294967602


memo4294967593 --> |clean|memo4294967593


signal4294967572 ===o |source|memo4294967590


memo4294967590 --> |clean|memo4294967590



signal4294967572 --> |clean|signal4294967572

signal4294967572 ===> |dirten|effect4294967585

memo4294967594 ===o |sub|signal4294967546



signal4294967546 --> |clean|signal4294967546

memoChain4294967547 ===o |source|observer4294967648

signal4294967572 ===o |source|observer4294967648

signal4294967575 ===o |source|observer4294967648

signal4294967576 ===o |source|observer4294967648
signal4294967576(" 'Layout tree' signal: rsact_ui::layout::Layout (clean)")

memo4294967594 ===o |sub|signal4294967576



signal4294967576 --> |clean|signal4294967576

memoChain4294967577 ===o |source|observer4294967648

memo4294967579 ===o |source|observer4294967648
memo4294967579([" 'Viewport' memo: rsact_ui::layout::size::Size (clean)"])

memo4294967594 ===o |sub|memo4294967579

observer4294967648 ===o |sub|memo4294967579


memo4294967578 ===o |source|memo4294967579
memo4294967578([" memo: embedded_graphics_core::geometry::size::Size (clean)"])

memo4294967579 ===o |sub|memo4294967578



memo4294967578 --> |clean|memo4294967578


memo4294967579 --> |clean|memo4294967579

signal4294967584 ===o |source|observer4294967648
signal4294967584(" 'Page state' signal: rsact_ui::widget::ctx::PageState<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>> (clean)")

observer4294967648 ===o |sub|signal4294967584



signal4294967584 --> |clean|signal4294967584

signal4294967596 ===o |source|observer4294967648
signal4294967596(" 'Force redraw' signal: () (dirty)")

observer4294967648 ===o |sub|signal4294967596



signal4294967596 --> |dirten|signal4294967596

observer4294967648 ===o |source|observer4294967648


observer4294967648 --> |clean|observer4294967648


observer4294967647 --> |clean|observer4294967647


signal4294967536 ===o |source|memo4294967594

signal4294967537 ===o |source|memo4294967594
signal4294967537(" signal: rsact_ui::layout::Layout (clean)")

memo4294967594 ===o |sub|signal4294967537




memo4294967539 ===o |source|memo4294967594
memo4294967539([" memo: alloc::string::String (clean)"])

memo4294967594 ===o |sub|memo4294967539



memo4294967539 --> |clean|memo4294967539

signal4294967541 ===o |source|memo4294967594

memo4294967543 ===o |source|memo4294967594

signal4294967544 ===o |source|memo4294967594

signal4294967546 ===o |source|memo4294967594

signal4294967548 ===o |source|memo4294967594
signal4294967548(" signal: rsact_ui::font::FontSize (clean)")

memo4294967594 ===o |sub|signal4294967548



signal4294967548 --> |clean|signal4294967548

signal4294967549 ===o |source|memo4294967594
signal4294967549(" signal: rsact_ui::layout::Layout (clean)")

memo4294967594 ===o |sub|signal4294967549




memo4294967551 ===o |source|memo4294967594
memo4294967551([" memo: alloc::string::String (clean)"])

memo4294967594 ===o |sub|memo4294967551



memo4294967551 --> |clean|memo4294967551

signal4294967553 ===o |source|memo4294967594
signal4294967553(" signal: rsact_ui::layout::Layout (clean)")

effect4294967587 ===o |sub|signal4294967553
effect4294967587[[" effect: () (dirty)"]]


signal4294967553 ===o |source|effect4294967587

signal4294967554 ===o |source|effect4294967587

signal4294967554(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (clean)")

memo4294967555 ===o |sub|signal4294967554
memo4294967555([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (clean)"])

memo4294967594 ===o |sub|memo4294967555


signal4294967554 ===o |source|memo4294967555


memo4294967555 --> |clean|memo4294967555

effect4294967587 ===o |sub|signal4294967554



signal4294967554 --> |clean|signal4294967554

signal4294967554 ===> |dirten|effect4294967587

memo4294967594 ===o |sub|signal4294967553




memo4294967555 ===o |source|memo4294967594

signal4294967556 ===o |source|memo4294967594

signal4294967558 ===o |source|memo4294967594

signal4294967560 ===o |source|memo4294967594
signal4294967560(" signal: rsact_ui::font::FontSize (clean)")

memo4294967594 ===o |sub|signal4294967560



signal4294967560 --> |clean|signal4294967560

signal4294967561 ===o |source|memo4294967594
signal4294967561(" signal: rsact_ui::layout::Layout (clean)")

memo4294967594 ===o |sub|signal4294967561




memo4294967563 ===o |source|memo4294967594
memo4294967563([" memo: alloc::string::String (clean)"])

memo4294967594 ===o |sub|memo4294967563



memo4294967563 --> |clean|memo4294967563

signal4294967565 ===o |source|memo4294967594
signal4294967565(" signal: rsact_ui::layout::Layout (clean)")

effect4294967588 ===o |sub|signal4294967565
effect4294967588[[" effect: () (dirty)"]]


signal4294967565 ===o |source|effect4294967588

signal4294967566 ===o |source|effect4294967588

signal4294967566(" signal: alloc::vec::Vec<rsact_ui::el::El<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>>> (clean)")

memo4294967567 ===o |sub|signal4294967566
memo4294967567([" memo: alloc::vec::Vec<rsact_reactive::memo::Memo<rsact_ui::layout::Layout>> (clean)"])

memo4294967594 ===o |sub|memo4294967567


signal4294967566 ===o |source|memo4294967567


memo4294967567 --> |clean|memo4294967567

effect4294967588 ===o |sub|signal4294967566



signal4294967566 --> |clean|signal4294967566

signal4294967566 ===> |dirten|effect4294967588

memo4294967594 ===o |sub|signal4294967565




memo4294967567 ===o |source|memo4294967594

signal4294967568 ===o |source|memo4294967594

signal4294967570 ===o |source|memo4294967594

memo4294967573 ===o |source|memo4294967594

signal4294967574 ===o |source|memo4294967594
signal4294967574(" signal: rsact_ui::layout::Layout (clean)")

memo4294967594 ===o |sub|signal4294967574



signal4294967574 --> |clean|signal4294967574

signal4294967576 ===o |source|memo4294967594

memo4294967579 ===o |source|memo4294967594

signal4294967581 ===o |source|memo4294967594
signal4294967581(" signal: rsact_ui::font::FontCtx (clean)")

memo4294967594 ===o |sub|signal4294967581





memo4294967594 --> |clean|memo4294967594

observer4294967648 ===o |sub|signal4294967536



signal4294967536 --> |clean|signal4294967536




memoChain4294967540(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))













memoChain4294967550(((" memoChain: rsact_ui::widget::icon::IconStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memoChain4294967552(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))








signal4294967557(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967559(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))






memoChain4294967562(((" memoChain: rsact_ui::widget::icon::IconStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))





memoChain4294967564(((" memoChain: rsact_ui::widget::text::TextStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))








signal4294967569(" signal: rsact_ui::widget::button::ButtonState (clean)")





memoChain4294967571(((" memoChain: rsact_ui::widget::button::ButtonStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (dirty)")))












signal4294967580(" signal: rsact_ui::page::dev::DevTools (clean)")






signal4294967583(" signal: rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (clean)")























signal4294967603(" 'Page state' signal: rsact_ui::widget::ctx::PageState<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>> (clean)")





memo4294967605([" memo: rsact_ui::widget::Meta (dirty)"])




memo4294967606([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (dirty)"])




memo4294967607([" 'Focusable' memo: alloc::vec::Vec<rsact_ui::el::ElId> (dirty)"])




memo4294967608([" 'Layout model' memo: rsact_ui::layout::LayoutModel (dirty)"])




signal4294967609(" 'Page style' signal: rsact_ui::page::PageStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (clean)")




signal4294967610(" 'Force redraw' signal: () (clean)")




signal4294967611(" 'Page state' signal: rsact_ui::widget::ctx::PageState<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>> (clean)")










memo4294967618([" memo: rsact_ui::widget::Meta (dirty)"])




memo4294967619([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (dirty)"])




memo4294967620([" 'Focusable' memo: alloc::vec::Vec<rsact_ui::el::ElId> (dirty)"])




memo4294967621([" 'Layout model' memo: rsact_ui::layout::LayoutModel (dirty)"])




signal4294967622(" 'Page style' signal: rsact_ui::page::PageStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (clean)")




signal4294967623(" 'Force redraw' signal: () (clean)")




signal4294967624(" 'Page state' signal: rsact_ui::widget::ctx::PageState<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>> (clean)")









memo4294967630([" memo: rsact_ui::widget::Meta (dirty)"])




memo4294967631([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (dirty)"])




memo4294967632([" 'Focusable' memo: alloc::vec::Vec<rsact_ui::el::ElId> (dirty)"])




memo4294967633([" 'Layout model' memo: rsact_ui::layout::LayoutModel (dirty)"])




signal4294967634(" 'Page style' signal: rsact_ui::page::PageStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (clean)")




signal4294967635(" 'Force redraw' signal: () (clean)")




signal4294967636(" 'Page state' signal: rsact_ui::widget::ctx::PageState<rsact_ui::widget::ctx::Wtf<rsact_ui::render::buffer::BufferRenderer<embedded_graphics_core::pixelcolor::binary_color::BinaryColor>, rsact_ui::style::NullStyler, &str>> (clean)")






memo4294967639([" memo: rsact_ui::widget::Meta (dirty)"])




memo4294967640([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (dirty)"])




memo4294967641([" memo: rsact_ui::widget::Meta (dirty)"])




memo4294967642([" memo: alloc::vec::Vec<rsact_reactive::memo::MemoTree<rsact_ui::widget::Meta>> (dirty)"])




memo4294967643([" 'Focusable' memo: alloc::vec::Vec<rsact_ui::el::ElId> (dirty)"])




memo4294967644([" 'Layout model' memo: rsact_ui::layout::LayoutModel (dirty)"])




signal4294967645(" 'Page style' signal: rsact_ui::page::PageStyle<embedded_graphics_core::pixelcolor::binary_color::BinaryColor> (clean)")




signal4294967646(" 'Force redraw' signal: () (clean)")





